# Generated by Django 2.0.5 on 2018-06-04 06:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20180604_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='sent_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
