# Generated by Django 2.0.6 on 2018-06-04 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_auto_20180604_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='user_id',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='Content',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='Com_id',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='dweet',
            old_name='Content',
            new_name='dweet',
        ),
        migrations.RemoveField(
            model_name='follower',
            name='No_of_followers',
        ),
        migrations.RemoveField(
            model_name='likes',
            name='No_likes',
        ),
        migrations.AddField(
            model_name='follower',
            name='follow_no',
            field=models.ManyToManyField(related_name='follows', to='login.Follower'),
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
