# Generated by Django 2.0.6 on 2018-06-04 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_auto_20180604_1447'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likes',
            old_name='Lik_id',
            new_name='Liker_id',
        ),
    ]
