# Generated by Django 2.0.6 on 2018-06-04 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_auto_20180604_1452'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follower',
            old_name='follower_no',
            new_name='n_follower',
        ),
    ]
